destination: ./_site
lsi: false
port: 4000
markdown: kramdown
highlighter: rouge
permalink: pretty
exclude: ['readme.markdown', 'Gemfile.lock', 'Gemfile', 'docker-compose.yml', 'circle.yml', 'Rakefile', 'vendor']
title: Sane Men
description: SengMing Tan's corner of the Internet
kramdown:
  input: GFM
  syntax_highlighter: rouge
feed:
  path: rss.xml
plugins:
  - jekyll-feed
  - jekyll-sitemap
